---
project:
    folderPath: /home/jovyan/work/process/data
    # The Docker folder where data resources for the project are located
    units: m
    # Units used by the coordinate reference system
    units_full: metres
    # Full name for the units
    study_buffer: 1600
    # Study region buffer, to account for edge effects
    buffered_study_region_name: 1600 m study region buffer
    # Buffered study region's name for map display purposes
    hex_diag: 250
    # Hexagon diagonal length and buffer distance (metres); hexagon sides will be half the length of this value; hexagon area is 3/2 * sqrt(3) * (hex_diag/2)^2; so with diag of 3000 m, area is 5845671.476 sq.m.
    hex_buffer: 250
    # Hexagon buffer distance, to account for edge effects
    multiprocessing: 6
    # Number of processors to use in multiprocessing scripts
    no_forward_edge_issues: 0
    # Used to flag and mitigate potential geometry discrepencies
    year: 2020
    # The year being targetted by this analysis
sql:
    admin_db: postgres
    # SQL settings to connect to Postgresql+Postgis Docker container
    db_host: 127.0.0.1
    db_port: 5433
    db_user: ghscic
    db_pwd: huilhuil!42
osm:
    osm_data: planet-latest_2020-08-13.osm.pbf
    # Downloaded OpenStreetMap (OSM) data
    osm_date: 20200813
    # Date at which OSM download was current
    osmnx_retain_all: False
    # If false, only retain main connected network when retrieving OSM roads
sample_points:
    points_id: location_id
    # sampling points unique id
    points: sampling_points
    # name of point data locations used for sampling
    point_sampling_interval: 30
    # interval in metres along which network is to be sampled
network_analysis:
    pedestrian: |-
         ["highway"]
         ["area"!~"yes"] 
         ["highway"!~"motor|proposed|construction|abandoned|platform|raceway"]
         ["foot"!~"no"]  
         ["service"!~"private"] 
         ["access"!~"private"]
    # query used for custom network in OSMnx
    distance: 1600
    # sausage buffer network size  -- in units specified above
    tolerance: 500
    # buffer distance for network lines as sausage buffer 
    line_buffer: 50
    # distance is a limit beyond which not to search for destinations
    limit: 1600
    # Distance within which all Areas of Open Space are sought
    aos_threshold: 1600
    # For scaling binary cutoffs using a smooth transition; this parameter adjusts slope k of the transition
    soft_threshold_slope: 5
    # search tolderance (in units specified above; features outside tolerance not located when adding locations); may need to increase if no locations are found
documentation:
    authors: Global Healthy Liveable Cities Indicator Study Collaboration
    # Authors of project
    version: 1.2
    # Version of documentation
    default_interactive_map: na
    # The default first map shown in 'interactive maps' section
points_of_interest:
    destination_list: [supermarket_osm, bakery_osm, meat_seafood_osm, fruit_veg_osm, deli_osm, convenience_osm, petrolstation_osm, newsagent_osm, market_osm, pt_any]
    osm_destination_definitions: /home/jovyan/work/process/configuration/osm_destination_definitions.csv
areas_of_interest:
    open_space: /home/jovyan/work/process/configuration/osm_open_space.yml
regions_of_interest:
    regions: /home/jovyan/work/process/configuration/regions.yml
datasets:
    gtfs:
        analysis_period: ['07:00:00', '19:00:00']
        headway_intervals: [20,30]
        dissolve_cities: ['hanoi']
        # aggregate mean of headways by stop_id; does not retain mode
    population:
        pop_min_threshold: 5
        # urban sample points intersecting hex grid cells with estimated population less than this will be excluded from analysis
        alias: ghs_pop_2015_wgs84_2019a
        name_f: "Global Human Settlements population data: 2015, WGS84 (EU JRC, 2019)"
        data_name: GHS-POP
        data_dir: ./data/GHS/WGS84
        data_type: raster:Int64
        epsg_name: WGS84
        epsg: 4326
        source_url: https://ghsl.jrc.ec.europa.eu/ghs_pop2019.php
        date_acquired: 20191101
        year_published: 2019
        year_target: 2015
        provider: EU JRC
        licence: CC BY 4.0
        licence_url: https://creativecommons.org/licenses/by/4.0/deed.ast
        resolution: 9 arcsec
        raster_band: 1
        raster_statistic: mean
        raster_nodata: -200
    urban_region:
        name_f: "Global Human Settlements urban centres: 2015 (EU JRC, 2019)"
        data_name: GHS-URBAN
        data_dir: ./data/GHS/GHS_STAT_UCDB2015MT_GLOBE_R2019A/GHS_STAT_UCDB2015MT_GLOBE_R2019A_V1_2.gpkg
        data_type: vector
        epsg_name: WGS84
        epsg: 4326
    ghsl_covariates: 
        air_pollution:
            E_EC2E_T15:
                Units: t a?¹
                Unit description: tonnes per annum
                Description: Total emission of CO 2 from the transport sector, using non-short-cycle-organic fuels in 2015
            E_EC2O_T15:
                Units: t a?¹
                Unit description: tonnes per annum
                Description: Total emission of CO 2 from the energy sector, using short-cycle-organic fuels in 2015
            E_EPM2_T15:
                Units: t a?¹
                Unit description: tonnes per annum
                Description: Total emission of PM 2.5 from the transport sector in 2015
            E_CPM2_T14:
                Units: µg m?³
                Unit description: micrograms per cubic meter
                Description: Total concertation of PM 2.5 for reference epoch 2014
