# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Global Healthy and Sustainable City Indicators"
subtitle: "FAQ"
email:
description: >- # this means to ignore newlines until "baseurl:"
  An open-source tool for calculating spatial indicators for healthy, sustainable cities worldwide using open or custom data.
minimal_mistakes_skin: mint
search: false
url: https://global-healthy-liveable-cities.github.io
baseurl: /global-indicators

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Australia/Melbourne

include:
  - assets/images/favicon.ico
  - _pages
 

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Global Healthy and Sustainable City Indicators Collaboration"
  avatar : "https://i0.wp.com/www.healthysustainablecities.org/wp-content/uploads/2022/04/mapa-mundo.png?resize=1024%2C560&ssl=1"
  bio    : "Global Healthy and Sustainable City-Indicators Collaboration aims to identify, measure and monitor health-related urban policy and spatial indicators in cities worldwide, to support planning for healthier and more equitable cities."
  links:
    - label: "Global Observatory for Healthy and Sustainable Cities"
      icon: "https://i0.wp.com/www.healthysustainablecities.org/wp-content/uploads/2022/05/cropped-GOHSC-favicon.png?fit=32%2C32&ssl=1"
      url: "https://healthysustainablecities.org/"

#footer:
#  links:
#    - label: "Global Observatory for Healthy and Sustainable Cities"
#      icon: assets/images/favicon.ico
#      url: "https://healthysustainablecities.org/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
